# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'Know the Quote' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for Know the Quote
  
  # Firebase
  pod 'Firebase/Analytics'
  pod 'Firebase/Database'
  pod 'Firebase/Firestore'
  # Optionally, include the Swift extensions if using Swift.
  pod 'FirebaseFirestoreSwift'
  

end
